name: clinical-trials-gov-data-dev
channels:
  - conda-forge
  - nodefaults
platforms:
  - linux-64
  - osx-arm64
category: main
dependencies:
  - "python =3.12"
  - pip >=21.2
  - PyPDF2
  - pandas >1,<3
